(deftheme dprandle-dark
  "Created 2023-02-03.")

(custom-theme-set-faces
 'dprandle-dark
 '(default ((t (:family "Ubuntu Mono" :foundry "DAMA" :width normal :height 112 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "wheat" :background "#1e1e1e" :stipple nil :inherit nil))))
 '(company-tooltip ((t (:background "#252525"))))
 '(company-tooltip-selection ((t (:background "#04395e"))))
 '(compilation-info ((t (:foreground "gray"))))
 '(cursor ((t (:background "green2"))))
 '(diff-file-header ((t (:inherit region :extend t :weight bold))))
 '(diff-header ((t (:inherit region :extend t))))
 '(ediff-current-diff-C ((t (:extend t :background "DarkOrange4"))))
 '(ediff-even-diff-A ((t (:inherit highlight :extend t))))
 '(ediff-even-diff-Ancestor ((t (:inherit highlight :extend t))))
 '(ediff-even-diff-B ((t (:inherit highlight :extend t))))
 '(ediff-even-diff-C ((t (:inherit highlight :extend t))))
 '(ediff-odd-diff-A ((t (:inherit region :extend t))))
 '(ediff-odd-diff-Ancestor ((t (:inherit highlight :extend t))))
 '(ediff-odd-diff-B ((t (:inherit region :extend t))))
 '(ediff-odd-diff-C ((t (:inherit region :extend t))))
 '(lsp-face-highlight-read ((t (:foreground "#9cdcfe" :underline t))))
 '(lsp-face-semhl-default-library ((t (:inherit nil))))
 '(lsp-face-semhl-interface ((t nil)))
 '(lsp-face-semhl-keyword ((t nil)))
 '(lsp-face-semhl-method ((t (:inherit lsp-face-semhl-function :weight normal))))
 '(lsp-face-semhl-parameter ((t (:inherit font-lock-variable-name-face :foreground "#9cdcfe"))))
 '(lsp-ui-peek-filename ((t (:foreground "seashell1" :weight bold))))
 '(lsp-ui-peek-header ((t (:background "#1a1a1a" :foreground "seashell1" :box (:line-width 2 :color "#3794FF") :weight bold))))
 '(lsp-ui-peek-highlight ((t (:background "DarkOrange4"))))
 '(lsp-ui-peek-line-number ((t (:foreground "gray70"))))
 '(lsp-ui-peek-list ((t (:background "#191919"))))
 '(lsp-ui-peek-peek ((t (:background "#001F33"))))
 '(lsp-ui-peek-selection ((t (:inherit region))))
 '(magit-blame-highlight ((t (:inherit region :extend t))))
 '(magit-diff-hunk-heading ((t (:inherit region :extend t))))
 '(magit-diff-hunk-heading-highlight ((t (:inherit highlight :extend t))))
 '(magit-section-highlight ((t (:inherit region))))
 '(mc/cursor-face ((t (:inherit cursor :foreground "black"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "medium blue"))))
 '(highlight ((t (:underline (:color foreground-color :style line) :foreground "orchid"))))
 '(region ((t (:background "#264f78" :extend t))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:extend t :background "yellow1")) (((class color) (min-colors 88) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:extend t :background "yellow")) (((class color) (min-colors 16) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 8)) (:extend t :foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "orchid"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#6A9955"))))
 '(font-lock-constant-face ((t (:foreground "#4FC1FF"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:weight bold :foreground "salmon"))))
 '(font-lock-keyword-face ((t (:weight normal :foreground "#569cd6"))))
 '(font-lock-negation-char-face ((t (:foreground "#9cdcfe"))))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#CE9178"))))
 '(font-lock-type-face ((t (:foreground "#4ec9b0"))))
 '(font-lock-variable-name-face ((t (:foreground "wheat1" :weight normal))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(button ((t (:underline (:color foreground-color :style line) :inherit nil))))
 '(link ((((class color) (min-colors 88) (background light)) (:underline (:color foreground-color :style line) :foreground "RoyalBlue3")) (((class color) (background light)) (:underline (:color foreground-color :style line) :foreground "blue")) (((class color) (min-colors 88) (background dark)) (:underline (:color foreground-color :style line) :foreground "cyan1")) (((class color) (background dark)) (:underline (:color foreground-color :style line) :foreground "cyan")) (t (:inherit (underline)))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((((class color) (background light)) (:background "grey95")) (((class color) (background dark)) (:background "grey10")) (t (:background "gray"))))
 '(header-line ((default (:inherit (mode-line))) (((type tty)) (:underline (:color foreground-color :style line) :inverse-video nil)) (((class color grayscale) (background light)) (:box nil :foreground "grey20" :background "grey90")) (((class color grayscale) (background dark)) (:box nil :foreground "grey90" :background "grey20")) (((class mono) (background light)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "black" :background "white")) (((class mono) (background dark)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "white" :background "black"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((((class color) (min-colors 88)) (:foreground "black" :background "grey75" :box (:line-width -1 :color nil :style released-button))) (t (:inverse-video t))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((default (:inherit (mode-line))) (((class color) (min-colors 88) (background light)) (:background "grey90" :foreground "grey20" :box (:line-width -1 :color "grey75" :style nil) :weight light)) (((class color) (min-colors 88) (background dark)) (:background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
 '(isearch ((((class color) (min-colors 88) (background light)) (:foreground "lightskyblue1" :background "magenta3")) (((class color) (min-colors 88) (background dark)) (:foreground "brown4" :background "palevioletred2")) (((class color) (min-colors 16)) (:foreground "cyan1" :background "magenta4")) (((class color) (min-colors 8)) (:foreground "cyan1" :background "magenta4")) (t (:inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 88) (background light)) (:background "paleturquoise")) (((class color) (min-colors 88) (background dark)) (:background "paleturquoise4")) (((class color) (min-colors 16)) (:background "turquoise3")) (((class color) (min-colors 8)) (:background "turquoise3")) (t (:underline (:color foreground-color :style line)))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'dprandle-dark)
